### ISSUE TITLE
mistake in memory header including macro

### ISSUE THREAD

**Issue by Harold2017** [mattreecebentley/plf_reorderase#1]
`std::to_address` is introduced in C++20, so the following macro is incorrect:

```C++
#ifndef PLF_CPP20_SUPPORT  // should be `#ifdef PLF_CPP20_SUPPORT`
	#include <memory> // std::to_address
#endif
```

**Comment by mattreecebentley** [comment]
Hey, actually spotted this independently last night and fixed (great minds think alike!).
Thanks though, let me know if you spot anything else.

**Comment by Harold2017** [comment]
> Hey, actually spotted this independently last night and fixed (great minds think alike!). Thanks though, let me know if you spot anything else.

yes, i would like to tell you the problem of your array release with `delete tmp`, but just saw you fix it in latest commit XD.
BTW, why not use `std::unique_ptr` since it was introduced in C++11?

**Comment by mattreecebentley** [comment]
Because it's not supported under C++98/03, which my stuff supports. Also, there's no compelling need for it.

**Comment by mattreecebentley** [comment]
ps. Thank you for (almost) pointing out the delete bug - rookie mistake, I haven't used anything but allocator_traits for allocation for so long I'd forgotten until clang told me :)

**Comment by Harold2017** [comment]
another kindly reminder, you may forget to use your `void_cast` function to replace `static_cast<void *>(&* x)`, :)

**Comment by mattreecebentley** [comment]
Good point, to_address does work with contiguous_iterator types, so that should work. Thanks-
Any thoughts regarding whether the allocation in reorderase(first, last) for types which may throw should occur via the container's allocator, or just via std::allocator, or via a user-specified allocator?

**Comment by Harold2017** [comment]
Well, i have quite limited experiences on exception handling in allocation failure case. Apart from the default `std::allocator` or some similar ones from 3rd party lib (e.g. `tcmalloc` by replacing `new`/`delete`), i only used the `std::pmr` ones. And i think the [memory resource](https://en.cppreference.com/w/cpp/memory/memory_resource) abstraction is good enough for my daily dev. In my opinion, the current way you use with `std::allocator_traits` is suitable.
